### ISSUE TITLE
React-confirm using really old react dependency

### ISSUE THREAD

**Issue by vesakilp** [haradakunihiko/react-confirm#13]
Used react dependency is really old, and leads to problems with shrinkwrap, basically it can't be used when using new react versions.

**Comment by joshwcomeau** [comment]
Yeah, I'm using it with React 16 and it works without issue (really great project, by the way, @haradakunihiko!). Should be a simple matter of incrementing the peerDependency to `^0.14.7 || 15.x || 16.x`

**Comment by haradakunihiko** [comment]
Thanks for using react-confirm. I'd really like to modify and also update the example to use the latest React version, but currently have no time for this.
Could you kindly create a PR for this if possible?

**Comment by joshwcomeau** [comment]
Sent a quick PR that adds the peer dependency update, and changes the example in the README to use `prop-types` package (since `PropTypes` is no longer included in React).

I just saw that there are also a couple example apps, which I realize now is probably what you meant by "update the example", but I'm afraid I don't quite have time for that. FWIW, I don't believe anything else needs to change other than moving `PropTypes` and `createClass` (if used) into separate packages.

**Comment by haradakunihiko** [comment]
Thanks for the PR, your comment was helpful since I haven't used react for a while.
Merged and published. (Maybe I will release again once react@16 are published. )
