### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by gabrielchang** [haradakunihiko/react-confirm#2]
Hi,

When no cancel function is provided on confirm.then, we've got this error.

Example

```
confirm('Are you sure')
      .then( () => console.log('proceed') )
```

Is there a way to manage it when no need for cancel func ?

**Comment by haradakunihiko** [comment]
Sorry for the late reply.
In the example, it is necessary to define reject function because it calls `cancel` function  on clicking cancel button. (https://github.com/haradakunihiko/react-confirm/blob/master/example/react-bootstrap/src/components/Confirmation.js#L30)

In this case, you need to call confirm function like 

```js
confirm('Are you sure')
      .then( () => console.log('proceed') , () => {console.log('cancel')})
```

If you don't like this behavior, you just simply call `dismiss` on cancel click like bellow. Thus, you do not need to define callback function for reject. 

```html
          <Modal.Footer>
            <Button onClick={cancel}>{cancelLabel}</Button>
            <Button className='button-l' bsStyle="primary" onClick={proceed}>{okLabbel}</Button>
          </Modal.Footer>
```
