### ISSUE TITLE
`options` is missing on type `ConfirmDialogProps`

### ISSUE THREAD

**Issue by silverwind** [haradakunihiko/react-confirm#87]
<img width="1105" alt="image" src="https://github.com/haradakunihiko/react-confirm/assets/115237/85044a18-ea57-40e9-ade6-75c6c7456347">

Should be here:

https://github.com/haradakunihiko/react-confirm/blob/7f62297e053e7b5046ce4f8dc2e9e31cab24aa9f/typescript/index.d.ts#L11-L20

**Comment by haradakunihiko** [comment]
The type of properties used within a dialog component, such as `options`, is not defined by the library but rather is passed as user-defined Props types to the generics of ConfirmDialog. Please define options as shown below.

```tsx
import { confirmable, ConfirmDialog } from 'react-confirm';

export interface Props {
  options: {};
};

const Confirmation: ConfirmDialog<Props, boolean> = ({show, proceed, options}) => (
  <Dialog onHide={() => proceed(false)} show={show}>
    {confirmation}
    <button onClick={() => proceed(false)}>CANCEL</button>
    <button onClick={() => proceed(true)}>OK</button>
  </Dialog>
);

export const confirm = confirmable(Confirmation);
```

Props defined on ConfirmDialog are merged with show, processed, and other props by confirmable and then passed to ConfirmDialog.

Due to some potentially misleading information in the README, I have updated the README on GitHub. Please also check the sample below.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/haradakunihiko/react-confirm-sample/tree/main/1_typescript)

**Comment by silverwind** [comment]
Thanks, got it to work:

```jsx
import type {ConfirmDialog} from "react-confirm";
import type {ReactNode} from "react";

type ConfirmDialogProps = {
  options: {
    text: ReactNode,
  };
};

export const ConfirmationDialog: ReactConfirmDialog<ConfirmDialogProps, boolean> = ({show, proceed, options: {text}}) => {
  if (!show) return null;
  return (
    <MyConfirmDialog
      text={text}
      onConfirm={() => proceed(true)}
      onCancel={() => proceed(false)}
    />
  );
};
